### ISSUE TITLE
Put all drivers in image?

### ISSUE THREAD

**Issue by realdannys** [timsutton/brigadier#9]
Hi Tim,

Great app, I think it will be just what we need to deploy to our macs we set up for customers that want Windows installed as default.

Ideally, what id do is deploy my generzlied sysprepped clone - boot it for them once so all the drivers are installed and then when it came to start setting up the system, shut down with CTRL+F10 and typing "shutdown /s" that way our novice users will be presenter with their Win 7 or Win 8.1 OOBE screen without any long wait or driver downloads/restarts

The problem with this for me is, we have a really slow internet connection, so continually loading the drivers is a nightmare - would it not make more sense to have all the drivers available in Apple's Boot Camp catalog within the image? Is there a reason for this? (huge size?) - failing that, how about on an external drive...I suppose the issue here is the same as the network one, you don't have Thunderbolt/USB3 support straight away?

So presumably the custom URL case would be for us to server them on our LAN? At least then the computer would be getting them are near gigabit speeds instead of over our dire internet - do you have a tutorial on how we might be able to grab all the ESD and drivers for all the current Mac's in the Apple Store and the catalog file to host them on our internet/lan server?

**Comment by timsutton** [comment]
Hi Dan,

You can certainly include the drivers yourself in the image - we used to do this before, but found it tricky once we wanted to be able to start mixing different generations of hardware (and easily support new hardware that might arrive).

The option to put in a `brigadier.plist` with the custom URL is, yes, for you to offer them via a software update catalog of your own choosing. This would be a catalog you're mirroring from Apple using Reposado or Apple's Software Update service in Server. A future version of the tool will search multiple catalogs instead of only a single one.

I use Reposado for managing software update catalogs for OS X clients, and so I make sure that the Boot Camp ESD updates are available in a given branch and set the brigadier.plist file to point to the catalog at that URL.

**Comment by realdannys** [comment]
Hi Tim,

Thanks for your reply - I managed to figure it out since I e-mailed you and have hosted my own server on the Mac mini using Nginx - its a life saver for someone with such diabolical internet speed at home! I did it manually by ripping the ESD’s from Apples site and changing the URLs manually though, which will make it harder to update per model I think so i’ll look into the Reposado solution.

I don’t think i’ve had any issues other than i’ve been working on some of the new Macbook Air’s and at the end of unpacking I get a pop up error saying the setup file doens’t exist which needs user interaction - I click it and then Bootcamp setup happens anyway. I’m not sure if its one thing missing - I don’t know if its my own server (though I can’t see it?) or if Apple have slightly modified something in the latest ESD?

Just for a bit of info for you, this is how i’ve been using Brigadier to deploy. I have a Win 7 and a Win 8.1 clone I deploy with Winclone and i’ve set the unattend to generalize into audit mode. It then boots into Audit and runs Brigadier, then it runs another script of mine which checks for Windows updates and applies them makes a few changes and then it runs sysprep again but without generalize into OOBE. When the user turns on the boot camp drivers are installed and everything is up to date ready for them to create an account! 

Kind Regards
Daniel Shepherd

**Comment by timsutton** [comment]
Thanks for the info!

I have no experience with audit mode; I'd often gotten the impression from MS documentation that it's normally used in cases where someone wants to manually "service" the image by adding new drivers or updates. If you'd ever like to provide me with some example unattend files and/or scripts I'd be happy to include these in the repo. It sounds like a useful workflow.

Closing this since you've opened #10 since to track the other issue with the 2015 Airs.
